# Generated by Django 2.0.7 on 2018-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary', models.TextField(default='About yourself', max_length=200)),
                ('current', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
