# Generated by Django 2.0.7 on 2018-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=30, unique=True)),
                ('Contact', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
